# Generated by Django 5.1.2 on 2024-11-03 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodconapp', '0003_chefregistration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregistration',
            old_name='password',
            new_name='passw',
        ),
    ]
