# Generated by Django 5.1.2 on 2024-11-03 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodconapp', '0004_rename_password_userregistration_passw'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregistration',
            old_name='passw',
            new_name='password',
        ),
    ]
