# Generated by Django 5.1.2 on 2024-11-03 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodconapp', '0005_rename_passw_userregistration_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='chefRegistration',
        ),
        migrations.DeleteModel(
            name='UserRegistration',
        ),
    ]
